import { useState, useEffect, useRef } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import {
  FiArrowRight, FiStar, FiCheck, FiZap, FiBarChart2,
  FiAward, FiClock, FiChevronDown, FiMoon, FiSun,
  FiMenu, FiX, FiShield, FiTrendingUp, FiTarget,
  FiMessageCircle
} from 'react-icons/fi';
import { BiBrain } from 'react-icons/bi';
import './LandingPage.css';

// ========================
// Data
// ========================
const features = [
  {
    icon: <BiBrain />,
    title: 'AI-Powered Questions',
    description: 'Dynamic questions generated by Google Gemini AI — never the same twice. Tailored to your chosen category and difficulty level.',
    color: '#6C63FF',
  },
  {
    icon: <FiBarChart2 />,
    title: 'Detailed Analytics',
    description: 'Get comprehensive reports with score breakdowns, strengths, weaknesses, and a personalized learning path after every interview.',
    color: '#FF6584',
  },
  {
    icon: <FiAward />,
    title: 'Global Leaderboard',
    description: 'Compete with developers worldwide. Track weekly and monthly rankings to see where you stand.',
    color: '#43E97B',
  },
  {
    icon: <FiTarget />,
    title: '17+ Categories',
    description: 'MERN, React, Node, Python, Java, C++, DBMS, OS, Networking, OOP, SQL — comprehensive coverage of CS fundamentals.',
    color: '#F59E0B',
  },
  {
    icon: <FiShield />,
    title: 'Real Evaluation',
    description: 'Every answer is evaluated by Gemini AI with a score, explanation of mistakes, better answer, and improvement suggestions.',
    color: '#3B82F6',
  },
  {
    icon: <FiTrendingUp />,
    title: 'Track Progress',
    description: 'Watch your skills grow over time with performance trends, achievement badges, and skill level progression.',
    color: '#A855F7',
  },
];

const stats = [
  { value: '17+', label: 'Interview Categories' },
  { value: '100%', label: 'AI-Powered Questions' },
  { value: '∞', label: 'Unique Interviews' },
  { value: '24/7', label: 'Always Available' },
];

const testimonials = [
  {
    name: 'Alex Thompson',
    role: 'Frontend Developer at Google',
    avatar: 'AT',
    text: 'This platform completely changed how I prepare for interviews. The AI feedback is incredibly detailed and helped me identify my weak areas.',
    rating: 5,
  },
  {
    name: 'Priya Sharma',
    role: 'Full-Stack Engineer at Amazon',
    avatar: 'PS',
    text: 'The questions feel real and challenging. I used this for 2 weeks before my Amazon interview and got the offer!',
    rating: 5,
  },
  {
    name: 'James Lee',
    role: 'Backend Developer at Microsoft',
    avatar: 'JL',
    text: 'The leaderboard feature keeps me motivated. The detailed reports show exactly what I need to study next. Highly recommend!',
    rating: 5,
  },
];

const faqs = [
  {
    q: 'How are interview questions generated?',
    a: 'All questions are dynamically generated by Google Gemini AI based on your chosen category, difficulty level, and question count. No two interviews are identical.',
  },
  {
    q: 'How is my answer evaluated?',
    a: 'Gemini AI evaluates your answer and provides a score (0-100), detailed explanation, mistakes identified, a model answer, and specific improvement suggestions.',
  },
  {
    q: 'Do I need an account to use the platform?',
    a: 'Yes, you need a free account to track your progress, save reports, and appear on the leaderboard. Registration takes under 30 seconds.',
  },
  {
    q: 'What categories are available?',
    a: 'We cover MERN, React, Node, Express, MongoDB, JavaScript, HTML, CSS, C++, Java, Python, DBMS, Operating Systems, Computer Networks, OOP, SQL, and Data Structures.',
  },
  {
    q: 'Can I retake an interview?',
    a: 'Absolutely! You can take unlimited interviews in any category. Your history is saved and you can filter, search, and view full reports for all past interviews.',
  },
];

// ========================
// Sub-components
// ========================
const FAQItem = ({ faq, index }) => {
  const [open, setOpen] = useState(false);
  return (
    <div className={`faq-item ${open ? 'faq-open' : ''}`} onClick={() => setOpen(!open)}>
      <div className="faq-question">
        <span>{faq.q}</span>
        <FiChevronDown className={`faq-icon ${open ? 'rotated' : ''}`} />
      </div>
      {open && <div className="faq-answer">{faq.a}</div>}
    </div>
  );
};

// ========================
// Main Landing Page
// ========================
const LandingPage = () => {
  const { isAuthenticated } = useAuth();
  const { theme, toggleTheme, isDark } = useTheme();
  const navigate = useNavigate();
  const [navOpen, setNavOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const heroRef = useRef(null);

  useEffect(() => {
    if (isAuthenticated) {
      navigate('/dashboard');
    }
  }, [isAuthenticated, navigate]);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 30);
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <div className="landing">
      {/* ============================
          Navbar
          ============================ */}
      <nav className={`landing-nav ${scrolled ? 'scrolled' : ''}`}>
        <div className="container landing-nav-inner">
          <Link to="/" className="landing-logo">
            <div className="landing-logo-icon"><BiBrain /></div>
            <span className="landing-logo-text">InterviewAI</span>
          </Link>

          <div className={`landing-nav-links ${navOpen ? 'mobile-open' : ''}`}>
            <a href="#features" onClick={() => setNavOpen(false)}>Features</a>
            <a href="#stats" onClick={() => setNavOpen(false)}>Stats</a>
            <a href="#testimonials" onClick={() => setNavOpen(false)}>Reviews</a>
            <a href="#faq" onClick={() => setNavOpen(false)}>FAQ</a>
          </div>

          <div className="landing-nav-actions">
            <button
              className="btn btn-ghost btn-icon"
              onClick={toggleTheme}
              aria-label="Toggle theme"
              id="landing-theme-btn"
            >
              {isDark ? <FiSun /> : <FiMoon />}
            </button>
            <Link to="/login" className="btn btn-ghost btn-sm">Login</Link>
            <Link to="/register" className="btn btn-primary btn-sm">
              Get Started <FiArrowRight />
            </Link>
          </div>

          <button
            className="landing-nav-hamburger"
            onClick={() => setNavOpen(!navOpen)}
            aria-label="Toggle menu"
          >
            {navOpen ? <FiX /> : <FiMenu />}
          </button>
        </div>
      </nav>

      {/* ============================
          Hero Section
          ============================ */}
      <section className="hero" ref={heroRef}>
        {/* Animated background orbs */}
        <div className="hero-bg">
          <div className="hero-orb hero-orb-1" />
          <div className="hero-orb hero-orb-2" />
          <div className="hero-orb hero-orb-3" />
          <div className="hero-grid" />
        </div>

        <div className="container hero-content">
          <div className="hero-badge animate-fadeInDown">
            <FiZap /> Powered by Google Gemini AI
          </div>

          <h1 className="hero-title animate-fadeInUp">
            Ace Your Next
            <br />
            <span className="hero-title-gradient">Technical Interview</span>
            <br />
            with AI Coaching
          </h1>

          <p className="hero-subtitle animate-fadeInUp" style={{ animationDelay: '100ms' }}>
            Practice with AI-generated questions, receive instant expert feedback,
            track your growth, and compete on the leaderboard. Your dream job is one interview away.
          </p>

          <div className="hero-cta animate-fadeInUp" style={{ animationDelay: '200ms' }}>
            <Link to="/register" className="btn btn-primary btn-xl" id="hero-cta-btn">
              Start Practicing Free <FiArrowRight />
            </Link>
            <Link to="/login" className="btn btn-ghost btn-xl">
              Sign In
            </Link>
          </div>

          <div className="hero-trust animate-fadeInUp" style={{ animationDelay: '300ms' }}>
            <div className="hero-trust-avatars">
              {['R', 'J', 'A', 'S', 'M'].map((l, i) => (
                <div key={i} className="hero-trust-avatar">{l}</div>
              ))}
            </div>
            <p>
              <strong>500+</strong> developers improving daily
            </p>
          </div>
        </div>

        {/* Hero floating card */}
        <div className="hero-card-preview animate-float">
          <div className="hero-card-inner card-glass">
            <div className="hero-card-header">
              <div className="hero-card-dot" style={{ background: '#EF4444' }} />
              <div className="hero-card-dot" style={{ background: '#F59E0B' }} />
              <div className="hero-card-dot" style={{ background: '#43E97B' }} />
              <span style={{ marginLeft: 'auto', color: 'var(--text-muted)', fontSize: '0.75rem' }}>
                React Interview — Medium
              </span>
            </div>
            <div className="hero-card-question">
              <p className="hero-card-label">Question 3 of 10</p>
              <p className="hero-card-text">
                What is the difference between <code>useMemo</code> and <code>useCallback</code> hooks in React?
              </p>
            </div>
            <div className="hero-card-score">
              <div className="hero-card-score-item">
                <span className="hero-card-score-label">AI Score</span>
                <span className="hero-card-score-value" style={{ color: 'var(--accent)' }}>87/100</span>
              </div>
              <div className="hero-card-score-item">
                <span className="hero-card-score-label">Confidence</span>
                <span className="hero-card-score-value" style={{ color: '#60A5FA' }}>Good</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ============================
          Stats Section
          ============================ */}
      <section className="landing-stats" id="stats">
        <div className="container">
          <div className="stats-grid">
            {stats.map((stat, i) => (
              <div key={i} className="stat-item">
                <div className="stat-value">{stat.value}</div>
                <div className="stat-label">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============================
          Features Section
          ============================ */}
      <section className="landing-section" id="features">
        <div className="container">
          <div className="section-header">
            <div className="section-badge">
              <FiZap /> Features
            </div>
            <h2 className="section-title">
              Everything You Need to
              <span className="text-gradient"> Land Your Dream Job</span>
            </h2>
            <p className="section-subtitle">
              A complete interview preparation system powered by state-of-the-art AI
            </p>
          </div>

          <div className="features-grid">
            {features.map((feature, i) => (
              <div key={i} className="feature-card card-hover" style={{ animationDelay: `${i * 80}ms` }}>
                <div
                  className="feature-icon"
                  style={{ background: `${feature.color}20`, color: feature.color }}
                >
                  {feature.icon}
                </div>
                <h3 className="feature-title">{feature.title}</h3>
                <p className="feature-desc">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============================
          How It Works
          ============================ */}
      <section className="landing-section how-it-works">
        <div className="container">
          <div className="section-header">
            <div className="section-badge">Process</div>
            <h2 className="section-title">
              Get Interview-Ready in
              <span className="text-gradient"> 3 Simple Steps</span>
            </h2>
          </div>

          <div className="steps-grid">
            {[
              {
                step: '01',
                title: 'Choose Your Interview',
                desc: 'Select your category, difficulty level, time limit, and number of questions.',
                icon: <FiTarget />,
              },
              {
                step: '02',
                title: 'Answer AI Questions',
                desc: 'Gemini AI generates unique questions. Type your answers in a distraction-free environment.',
                icon: <BiBrain />,
              },
              {
                step: '03',
                title: 'Get Expert Feedback',
                desc: 'Receive a detailed report with scores, mistakes, better answers, and a learning path.',
                icon: <FiBarChart2 />,
              },
            ].map((s, i) => (
              <div key={i} className="step-card">
                <div className="step-number">{s.step}</div>
                <div className="step-icon">{s.icon}</div>
                <h3>{s.title}</h3>
                <p>{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============================
          Testimonials
          ============================ */}
      <section className="landing-section" id="testimonials">
        <div className="container">
          <div className="section-header">
            <div className="section-badge">
              <FiMessageCircle /> Testimonials
            </div>
            <h2 className="section-title">
              Loved by
              <span className="text-gradient"> Developers Worldwide</span>
            </h2>
          </div>

          <div className="testimonials-grid">
            {testimonials.map((t, i) => (
              <div key={i} className="testimonial-card card-hover">
                <div className="testimonial-stars">
                  {Array.from({ length: t.rating }).map((_, j) => (
                    <FiStar key={j} />
                  ))}
                </div>
                <p className="testimonial-text">"{t.text}"</p>
                <div className="testimonial-author">
                  <div className="testimonial-avatar">{t.avatar}</div>
                  <div>
                    <p className="testimonial-name">{t.name}</p>
                    <p className="testimonial-role">{t.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============================
          FAQ Section
          ============================ */}
      <section className="landing-section" id="faq">
        <div className="container">
          <div className="section-header">
            <h2 className="section-title">
              Frequently Asked
              <span className="text-gradient"> Questions</span>
            </h2>
          </div>

          <div className="faq-list">
            {faqs.map((faq, i) => (
              <FAQItem key={i} faq={faq} index={i} />
            ))}
          </div>
        </div>
      </section>

      {/* ============================
          CTA Section
          ============================ */}
      <section className="landing-cta">
        <div className="container">
          <div className="cta-card">
            <div className="cta-orb" />
            <div className="section-badge" style={{ margin: '0 auto var(--space-6)' }}>
              <FiZap /> Start Today
            </div>
            <h2 className="cta-title">
              Ready to Ace Your Interview?
            </h2>
            <p className="cta-subtitle">
              Join hundreds of developers who improved their skills with AI-powered mock interviews.
            </p>
            <div className="cta-actions">
              <Link to="/register" className="btn btn-primary btn-xl" id="cta-register-btn">
                Get Started Free <FiArrowRight />
              </Link>
              <div className="cta-perks">
                {['No credit card', 'Free forever', 'Instant access'].map((p) => (
                  <span key={p} className="cta-perk">
                    <FiCheck /> {p}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ============================
          Footer
          ============================ */}
      <footer className="landing-footer">
        <div className="container">
          <div className="footer-inner">
            <div className="footer-brand">
              <Link to="/" className="landing-logo">
                <div className="landing-logo-icon"><BiBrain /></div>
                <span className="landing-logo-text">InterviewAI</span>
              </Link>
              <p className="footer-desc">
                AI-powered mock interview platform built to help developers land their dream jobs.
              </p>
            </div>
            <div className="footer-links-group">
              <h4>Platform</h4>
              <a href="#features">Features</a>
              <Link to="/register">Sign Up</Link>
              <Link to="/login">Login</Link>
            </div>
            <div className="footer-links-group">
              <h4>Categories</h4>
              <span>MERN Stack</span>
              <span>JavaScript</span>
              <span>Python</span>
              <span>Data Structures</span>
            </div>
          </div>
          <div className="footer-bottom">
            <p>© {new Date().getFullYear()} InterviewAI. Built with ❤️ using MERN + Google Gemini AI.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
